Refactor error handling and logging in NSM components
- Renamed bitfield256_err_code to Bitfield256 (CamelCase cpp-style)
- Added method clear to class Bitfield256 for better struct usage
- Changed method name from isBitSet to setBit and field isAnyBitSet
  to method to follow intended logic

Fixes jira https://jirasw.nvidia.com/browse/DGXOPENBMC-13701

Moved logging handling to log.hpp

- Changed macro logHandleResponseMsg to LG2_ERROR and LG2_ERROR_FILE
- Replaced <phosphor-logging/lg2.hpp> with stateChangeLogger.hpp
  in nsmObject.hpp.
- Updated various NSM components to use the new logging mechanism.
- Defined 2 log level macros types with different functionality:
  - `LG2_<LEVEL>`: Logs unconditionally with file, line, object
    name, and device ID. Use for detailed logging without rate limiting
    or when shouldLog() arguments mismatches.
  - `LG2_<LEVEL>_FLT`: Logs with flood prevention, including file, line,
    object name, and device ID. Use for controlled detailed logging.
- Added logging macros `LG2_EMERGENCY`, `LG2_ALERT`, `LG2_CRITICAL`,
  `LG2_ERROR`, `LG2_WARNING`, `LG2_NOTICE`, `LG2_INFO`, and `LG2_DEBUG`
  for various log levels.
- Implemented unit tests for all StateChangeLogger cases.

NOTE: StateChangeLogger allow only following types:
- bool
- nsm_reason_codes
- nsm_sw_codes
- nsm_completion_codes

Check shouldLog usage in case of compilation error like:
```
In file included from ../nsmd/test/stateChangeLogger_test.cpp:29:
../nsmd/stateChangeLogger.hpp:66:10: note: candidate: ‘template<class
 ... Args> bool nsm::StateChangeLogger::shouldLog(const std::string&,
Args&& ...) requires  AllStateChangeLoggerAllowedTypes<Args ...>’
   66 |     bool shouldLog(const std::string& loggerName, Args&&...
args)
      |          ^~~~~~~~~
../nsmd/stateChangeLogger.hpp:66:10: note:   template argument
deduction/substitution failed:
../nsmd/stateChangeLogger.hpp:66:10: note: constraints not satisfied
../nsmd/stateChangeLogger.hpp: In substitution of ‘template<class ...
Args> bool nsm::StateChangeLogger::shouldLog(const std::string&, Args&&
...) requires  AllStateChangeLoggerAllowedTypes<Args ...>
[with Args = {int}]’:
../nsmd/test/stateChangeLogger_test.cpp:176:14:   required from here
../nsmd/stateChangeLogger.hpp:40:9:   required for the satisfaction of
 ‘AllStateChangeLoggerAllowedTypes<Args ...>’ [with Args = {int}]
../nsmd/stateChangeLogger.hpp:41:44: note: the expression
‘(StateChangeLoggerAllowedType<Args> && ...) [with Args = {int}]’
evaluated to ‘false’
   41 |     (StateChangeLoggerAllowedType<Args> && ...);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
```

Fixes jira https://jirasw.nvidia.com/browse/DGXOPENBMC-13702

- Changed return values from NSM_ERR_INVALID_DATA to NSM_SW_ERROR_NULL
  in platform-environmental.c.
- Added `LG2_ERROR` calls to various handleResponseMsg methods
- Removed clearErrorBitMap and shouldLogError calls from
  handleResponseMsg methods and changed to shouldLog and `LG2_ERROR`
- Updated condition checks to use rc == NSM_SW_SUCCESS and
  cc == NSM_SUCCESS.
- Simplified return statements to use cc ? cc : rc.
- Updated test cases to reflect changes in error handling.

Fixes jira https://jirasw.nvidia.com/browse/DGXOPENBMC-13703

Refactor NsmEvent classes

- Modified various event handler classes to use the new
  `LG2_ERROR` and `LG2_ERROR_FILE` macros.

Fixes jira https://jirasw.nvidia.com/browse/DGXOPENBMC-13704

Refactor and improve error handling in NSM codebase

- Replace variable rc_ with rc for consistency.
- Replace reason_code with reasonCode for consistency.
- Add `LG2_ERROR` function calls to log
  responses.
- Simplify return statements to co_return cc ? cc : rc.
- Update class definitions to inherit from NsmObjectBase.
- Correct class name capitalization for ClearClockLimAsyncIntf.
- Remove redundant error logging and return statements.
- Improve readability and maintainability of the code.
- Removed lg2::debug which was flooding the nsmd binary call

Fixes jira https://jirasw.nvidia.com/browse/DGXOPENBMC-13705